linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    # - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    # - exportloopref
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - structcheck
    # - stylecheck
    - tparallel
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck
    - wsl
    - whitespace

# disable:
#    - exhaustivestruct
#    - ifshort
#    - goheader
#    - prealloc
#    - testpackage
#    - wrapcheck

linters-settings:
  gosec:
    excludes:
      - G601
  revive:
    rules:
      - name: var-naming
        severity: warning
        arguments:
          - ["ID"] # AllowList

issues:
  exclude-dirs:
    - "docs"
